### ISSUE TITLE
Confused exception: Values must be emitted before tables

### ISSUE THREAD

**Issue by Dragon-GCS** [samuelcolvin/rtoml#45]
Version: rtoml = 0.8.0, python = 3.8.6
system: win11

example toml file:
```toml
# pyproject.toml
[project]
dependencies=["fire", "rtoml"]

[[project.authors]]
name = "Dragon-GCS"
email = "87817321@qq.com"
```

Code which can work correctly, call it `code1`

```python

import rtoml

with open("pyproject.toml") as f:
    tom = rtoml.loads(f.read())

with open("regenerate.toml", "w") as f:
    rtoml.dump(tom, f)
```

When I print `tom`, it's a dict like that: 
```python
{'project': 
  {
    'authors': [{'email': '87817321@qq.com', 'name': 'Dragon-GCS'}],
    'dependencies': ['fire', 'rtoml']
  }
}
```

So I try to dump this dict to file with followed code: 
```python
tom = {
    'project': {
            'authors': [{'email': '87817321@qq.com', 'name': 'Dragon-GCS'}],
            'dependencies': ['fire', 'rtoml']
        }
    }
with open("regenerate.toml", "w") as f:
    rtoml.dump(tom, f)
```

There was an Exception:
```
Traceback (most recent call last):
  File "e:\ProjectFiles\Python\Start\test_rtoml.py", line 12, in <module>
    rtoml.dump(tom, f)
  File "e:\ProjectFiles\Python\Start\.venv\lib\site-packages\rtoml\__init__.py", line 57, in dump
    s = dumps(obj, pretty=pretty)
  File "e:\ProjectFiles\Python\Start\.venv\lib\site-packages\rtoml\__init__.py", line 48, in dumps
    return serialize(obj)
_rtoml.TomlSerializationError: values must be emitted before tables
```
Another, when switch `[project]` and `[[project.authors]]`, like that:

```toml
[[project.authors]]
name = "Dragon-GCS"
email = "87817321@qq.com"
[project]
dependencies=["fire", "rtoml"]
```
`code1` will raise `TomlSerializationError` too.

All the code was run correctly with **toml**(another toml parser package)

**Comment by samuelcolvin** [comment]
This error [comes from](https://github.com/alexcrichton/toml-rs/blob/cf867939add188abd7440f920d1883c8e098f4f4/src/ser.rs#L131-L134) the upstream toml library:

```rs
    /// All values in a TOML table must be emitted before further tables are
    /// emitted. If a value is emitted *after* a table then this error is
    /// generated.
    ValueAfterTable,
```

**Comment by samuelcolvin** [comment]
Might be a way to fix this in rtoml, happy to accept a PR.

**Comment by samuelcolvin** [comment]
By the way, toml has a lot of problems, see https://github.com/pwwang/toml-bench

**Comment by Dragon-GCS** [comment]
Ok, it happend only once, it works well in my work.
